basicapp/urls.py
from django.urls import path
from basicapp import views

app_name = 'basicapp'

urlpatterns=[
    path('register/', views.register , name='register'),
    path('login/', views.user_login , name='user_login'),
]

thirdproject/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basicapp/', include('basicapp.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
]

basicapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user=models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)

    profile_pic= models.ImageField(upload_to='profile_pics',blank=True)

    def str(self):
        return self.user.username

basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password= forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields= ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields =('portfolio_site','profile_pic')

basicapp/views.py
from django.shortcuts import render
from basicapp.forms import  UserProfileInfoForm,UserForm

#
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import login,logout,authenticate

# Create your views here.
def index(request):
    return render(request, 'basicapp/index.html')

@login_required
def special(request):
    return HttpResponse('login required')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



def register(request):

    registered= False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()
            registered=True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form= UserForm()
        profile_form= UserProfileInfoForm()

    return render(request, 'basicapp/registration_page.html', {'user_form':user_form,'profile_form':profile_form,'registered':registered})



def user_login(request):

    if request.method == 'POST':
        username= request.POST.get('username')
        password= request.POST.get('password')

        user= authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else :
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            print("Someone is trying to login")
            print("Username : {} and Password : {}".format(username,password))
            return HttpResponse("invalid login details")

    else:
        return render(request,'basicapp/login_page.html')

templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </head>
  <body>
    <!-- <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'index' %}" class="navbar-brand">Django</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basicapp:register' %}">register</a></li>
        </ul>
      </div>
    </nav> -->
    <!-- <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Page 1</a></li>
      <li><a href="#">Page 2</a></li>
      <li><a href="#">Page 3</a></li>
    </ul>
  </div>
</nav> -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'index' %}">Django <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
            <a class="nav-item nav-link" href="{% url 'basicapp:register' %}">REgistration</a>
            {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
              <a class="nav-item nav-link" href="{% url 'basicapp:user_login' %}">Login</a>
            {% endif %}
            <a class="nav-item nav-link" href="{% url 'special' %}">special</a>

          </div>
        </div>
      </div>

    </nav>
    <div class="container">
      {% block body-block %}
      {% endblock %}

    </div>
  </body>
</html>

templates/basicapp/index.html
{% extends "basicapp/base.html" %}
{% block body-block %}

<div class="jumbotron">
  <h1>Welcome to home page</h1>
</div>




{% endblock %}

templates/basicapp/login_page.html
{% extends 'basicapp/base.html' %}
{% block body-block %}
<div class="jumbotron">
  <h1>Please Login</h1>
  <form  action="{% url 'basicapp:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password" >

    <input type="submit" name="" value="Submit">

  </form>

</div>

{% endblock %}

templates/basicapp/registration_page.html
{% extends "basicapp/base.html" %}
{% load static %}
{% block body-block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Thanku for registeration</h1>
  {% else %}
    <h1>REgister form</h1>
    <h3>Fill Out form </h3>

    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">
    </form>
  {% endif %}

</div>
{% endblock %}